server:
  port: 4004

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4002" # Разрешаем Аналитике доступ
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        # --- PATIENT SERVICE ROUTE ---
        # REST CLIENT -> http://localhost:4004/api/patients
        # GATEWAY -> Auth Check -> StripPrefix(1) -> http://patient-service:4000/patients
        - id: patient-service-route
          uri: http://patient-service:4000
          predicates:
            - Path=/api/patients/**
          filters:
            - AuthenticationFilter # Your custom JWT logic
            - StripPrefix=1        # Removes "/api" before sending to microservice

        # --- AUTH SERVICE ROUTE ---
        # No AuthenticationFilter here, otherwise nobody could register/login!
        - id: auth-service-route
          uri: http://auth-service:5000
          predicates:
            - Path=/api/v1/auth/**

        # --- API DOCS FOR AUTH ---
        - id: api-docs-auth-route
          uri: http://auth-service:5000
          predicates:
            - Path=/api-docs/auth
          filters:
            - RewritePath=/api-docs/auth, /v3/api-docs

        # --- API DOCS ROUTE ---
        - id: api-docs-patient-route
          uri: http://patient-service:4000
          predicates:
            - Path=/api-docs/patients
          filters:
            - RewritePath=/api-docs/patients, /v3/api-docs
              
        # --- ANALYTICS SERVICE ROUTE ---
        - id: analytics-service-route
          uri: http://analytics-service:4002
          predicates:
            - Path=/api/analytics/**
          filters:
            - AuthenticationFilter
            - StripPrefix=1

          # --- API DOCS FOR ANALYTICS ---
        - id: api-docs-analytics-route
          uri: http://analytics-service:4002
          predicates:
            - Path=/api-docs/analytics
          filters:
            - RewritePath=/api-docs/analytics, /v3/api-docs

          # --- BILLING SERVICE ROUTE ---
        - id: billing-service-route
          uri: http://billing-service:4001
          predicates:
            - Path=/api/billing/**
          filters:
            - AuthenticationFilter
            - StripPrefix=1

          # --- API DOCS FOR BILLING ---
        - id: api-docs-billing-route
          uri: http://billing-service:4001
          predicates:
            - Path=/api-docs/billing
          filters:
            - RewritePath=/api-docs/billing, /v3/api-docs
jwt:
  # Public key path inside the gateway's resources
  public-key-path: /app/certs/public_key.der

management:
  endpoints:
    web:
      exposure:
        include: routes,health,info
